services:
  mockoon:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile do Mockoon
    ports:
      - "3000:3000" # Porta exposta para o Mockoon

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: desafio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: desafiosantander
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: